### PR TITLE
enable craft 5

### PR DESCRIPTION
**Pull request by obuchmann**
Update plugin like fortrabbit for craft 5.
https://github.com/fortrabbit/craft-object-storage/commit/c555b630d67a2c537db86432c057f5078e0bff4f

### CODE REVIEW

**Comment by behinddesign** [comment]
Haven't tested Craft 5- if no further changes are needed then please adjust composer.json to be backwards compatible with craft 4 in the composer json.

**Comment by obuchmann** [comment]
I added the craft 4 dependency. should work on 4 and 5 now. I also fixed a bug with the date helper.

**Review by behinddesign — APPROVED** [review]
Looks good! Thanks

**Comment by obuchmann** [comment]
@behinddesign  would you be so kind to release it to the craft 5 store thanks!

**Pull request merged**
